all:
	./compile.sh

run:
	./execute.sh -r -i query-test.xml -o ranked-list -m model -d CIRB010

time:
	time ./execute.sh -r -i query-test.xml -o ranked-list -m model -d CIRB010

diff:
	diff ranked-list ranked-list3

	
